### ISSUE TITLE
tail: cannot open '/data/data/com.termux/files/home/deboot_debian/debootstrap/debootstrap.log' for reading: No such file or directory

### ISSUE THREAD

**Issue by fahadali32** [Bhai4You/Termux-Os#4]
Why it's showing and what i have to do for this please help

**Comment by Bhai4You** [comment]
Install latest debian version pkg..
Refer Links :

- https://wiki.termux.com/wiki/Debian
- https://github.com/sp4rkie/debian-on-termux
